class EmojiUtil {
  static Map emojiCN = {
    '[微笑]': '/::)',
    '[撇嘴]': '/::~',
    '[色]': '/::B',
    '[发呆]': '/::|',
    '[得意]': '/:8-)',
    '[流泪]': '/::<',
    '[害羞]': r'/::$',
    '[闭嘴]': '/::X',
    '[睡]': '/::Z',
    '[大哭]': '/::\'(',
    '[尴尬]': '/::-|',
    '[发怒]': '/::@',
    '[调皮]': '/::P',
    '[呲牙]': '/::D',
    '[惊讶]': '/::O',
    '[难过]': '/::(',
    '[囧]': '[囧]',
    '[抓狂]': '/::Q',
    '[吐]': '/::T',
    '[偷笑]': '/:,@P',
    '[愉快]': '/:,@-D',
    '[白眼]': '/::d',
    '[傲慢]': '/:,@o',
    '[困]': '/:|-)',
    '[惊恐]': '/::!',
    '[流汗]': '/::L',
    '[憨笑]': '/::>',
    '[悠闲]': '/::,@',
    '[奋斗]': '/:,@f',
    '[咒骂]': '/::-S',
    '[疑问]': '/:?',
    '[嘘]': '/:,@x',
    '[晕]': '/:,@@',
    '[衰]': '/:,@!',
    '[骷髅]': '/:!!!',
    '[敲打]': '/:xx',
    '[再见]': '/:bye',
    '[擦汗]': '/:wipe',
    '[抠鼻]': '/:dig',
    '[鼓掌]': '/:handclap',
    '[坏笑]': '/:B-)',
    '[左哼哼]': '/:<@',
    '[右哼哼]': '/:@>',
    '[哈欠]': '/::-O',
    '[鄙视]': '/:>-|',
    '[委屈]': '/:P-(',
    '[快哭了]': '/::\'|',
    '[阴险]': '/:X-)',
    '[亲亲]': '/::*',
    '[可怜]': '/:8*',
    '[菜刀]': '/:pd',
    '[西瓜]': '/:<W>',
    '[啤酒]': '/:beer',
    '[咖啡]': '/:coffee',
    '[猪头]': '/:pig',
    '[玫瑰]': '/:rose',
    '[凋谢]': '/:fade',
    '[嘴唇]': '/:showlove',
    '[爱心]': '/:heart',
    '[心碎]': '/:break',
    '[蛋糕]': '/:cake',
    '[炸弹]': '/:bome',
    '[便便]': '/:shit',
    '[月亮]': '/:moon',
    '[太阳]': '/:sun',
    '[拥抱]': '/:hug',
    '[强]': '/:strong',
    '[弱]': '/:weak',
    '[握手]': '/:share',
    '[胜利]': '/:v',
    '[抱拳]': '/:@)',
    '[勾引]': '/:jj',
    '[拳头]': '/:@@',
    '[OK]': '/:ok',
    '[跳跳]': '/:jump',
    '[发抖]': '/:shake',
    '[怄火]': '/:<O>',
    '[转圈]': '/:circle',
    // '[嘿哈]': '[Hey]',
    // '[捂脸]': '[Facepalm]',
    // '[奸笑]': '[Smirk]',
    // '[机智]': '[Smart]',
    // '[皱眉]': '[Concerned]',
    // '[耶]': '[Yeah!]',
    // '[1F602]': '\u{1F602}'
    // '[转圈]': '/:circle',
    // '[转圈]': '/:circle',
    '[笑脸]': '[Happy]',
    '[生病]': '[Sick]',
    '[脸红]': '[Flushed]',
    '[破涕为笑]': '[Lol]',
    '[恐惧]': '[Terror]',
    '[失望]': '[LetDown]',
    '[无语]': '[Duh]',
    '[嘿哈]': '[Hey]',
    '[捂脸]': '[Facepalm]',
    '[奸笑]': '[Smirk]',
    '[机智]': '[Smart]',
    '[皱眉]': '[Concerned]',
    '[耶]': '[Yeah!]',
    '[吃瓜]': '[Onlooker]',
    '[加油]]': '[GoForIt]',
    '[汗]': '[Sweats]',
    '[天啊]': '[OMG]',
    '[Emm]': '[Emm]',
    '[社会社会]': '[Respect]',
    '[旺柴]': '[Doge]',
    '[好的]': '[NoProb]',
    '[打脸]': '[MyBad]',
    '[哇]': '[Wow]',
    '[翻白眼]': '[Boring]',
    '[666]': '[Awesome]',
    '[让我看看]': '[LetMeSee]',
    '[叹气]': '[Sigh]',
    '[苦涩]': '[Hurt]',
    '[裂开]': '[Broken]',
    '[合十]': '[Worship]',
    '[庆祝]': '[Party]',
    '[礼物]': '/:gift',
    '[红包]': '[Packet]',
    '[发]': '[Rich]',
    '[福]': '[Blessing]',
    '[烟花]': '[Fireworks]',
  };
  static Map emojiData = {
    '/::)': 'emoji_1',
    '/::~': 'emoji_2',
    '/::B': 'emoji_3',
    '/::|': 'emoji_4',
    '/:8-)': 'emoji_5',
    '/::<': 'emoji_6',
    '/::${r'$'}': 'emoji_7',
    '/::X': 'emoji_8',
    '/::Z': 'emoji_9',
    '/::\'(': 'emoji_10',
    '/::-|': 'emoji_11',
    '/::@': 'emoji_12',
    '/::P': 'emoji_13',
    '/::D': 'emoji_14',
    '/::O': 'emoji_15',
    '/::(': 'emoji_16',
    // '/::+': 'emoji_17',
    '[囧]': 'emoji_18',
    '/::Q': 'emoji_19',
    '/::T': 'emoji_20',
    '/:,@P': 'emoji_21',
    '/:,@-D': 'emoji_22',
    '/::d': 'emoji_23',
    '/:,@o': 'emoji_24',
    // '/::g': 'emoji_25',
    '/:|-)': 'emoji_26',
    '/::!': 'emoji_27',
    '/::L': 'emoji_28',
    '/::>': 'emoji_29',
    '/::,@': 'emoji_30',
    '/:,@f': 'emoji_31',
    '/::-S': 'emoji_32',
    '/:?': 'emoji_33',
    '/:,@x': 'emoji_34',
    '/:,@@': 'emoji_35',
    '/:,@!': 'emoji_37',
    '/:!!!': 'emoji_38',
    '/:xx': 'emoji_39',
    '/:bye': 'emoji_40',
    '/:wipe': 'emoji_41',
    '/:dig': 'emoji_42',
    '/:handclap': 'emoji_43',
    '/:B-)': 'emoji_45',
    '/:<@': 'emoji_46',
    '/:@>': 'emoji_47',
    '/::-O': 'emoji_48',
    '/:>-|': 'emoji_49',
    '/:P-(': 'emoji_50',
    '/::\'|': 'emoji_51',
    '/:X-)': 'emoji_52',
    '/::*': 'emoji_53',
    // '': 'emoji_54',
    '/:8*': 'emoji_55',
    '/:pd': 'emoji_56',
    '/:<W>': 'emoji_57',
    '/:beer': 'emoji_58',
    // '': 'emoji_59',
    // '': 'emoji_60',
    '/:coffee': 'emoji_61',
    // '': 'emoji_62',
    '/:pig': 'emoji_63',
    '/:rose': 'emoji_64',
    '/:fade': 'emoji_65',
    '/:showlove': 'emoji_66',
    '/:heart': 'emoji_67',
    '/:break': 'emoji_68',
    '/:cake': 'emoji_69',
    // '': 'emoji_70',
    '/:bome': 'emoji_71',

    // '': 'emoji_71',
    // '': 'emoji_72',
    // '': 'emoji_73',
    // '': 'emoji_74',
    '/:shit': 'emoji_75',
    '/:moon': 'emoji_76',
    '/:sun': 'emoji_77',
    // '': 'emoji_78',
    '/:hug': 'emoji_79',
    '/:strong': 'emoji_80',
    '/:weak': 'emoji_81',
    '/:share': 'emoji_82',
    '/:v': 'emoji_83',
    '/:@)': 'emoji_84',
    '/:jj': 'emoji_85',
    '/:@@': 'emoji_86',
    // '': 'emoji_87',
    // '': 'emoji_88',
    // '': 'emoji_89',
    '/:ok': 'emoji_90',
    // '': 'emoji_91',
    // '': 'emoji_92',
    '/:jump': 'emoji_93',
    '/:shake': 'emoji_94',
    '/:<O>': 'emoji_95',
    '/:circle': 'emoji_96',
    // '': 'emoji_97',
    // '': 'emoji_98',
    // '': 'emoji_99',
    // '': 'emoji_100',
    // '\u{1F602}': 'emoji_unicode'
    //
    '[Happy]': 'emoji_101',
    '[Sick]': 'emoji_102',
    '[Flushed]': 'emoji_103',
    '[Lol]': 'emoji_104',
    '[Terror]': 'emoji_105',
    '[LetDown]': 'emoji_106',
    '[Duh]': 'emoji_107',
    '[Hey]': 'emoji_108',
    '[Facepalm]': 'emoji_109',
    '[Smirk]': 'emoji_110',
    '[Smart]': 'emoji_111',
    '[Concerned]': 'emoji_112',
    '[Yeah!]': 'emoji_113',
    '[Onlooker]': 'emoji_114',
    '[GoForIt]': 'emoji_115',
    '[Sweats]': 'emoji_116',
    '[OMG]': 'emoji_117',
    '[Emm]': 'emoji_118',
    '[Respect]': 'emoji_119',
    '[Doge]': 'emoji_120',
    '[NoProb]': 'emoji_121',
    '[MyBad]': 'emoji_122',
    '[Wow]': 'emoji_123',
    '[Boring]': 'emoji_124',
    '[Awesome]': 'emoji_125',
    '[LetMeSee]': 'emoji_126',
    '[Sigh]': 'emoji_127',
    '[Hurt]': 'emoji_128',
    '[Broken]': 'emoji_129',
    '[Worship]': 'emoji_130',
    '[Party]': 'emoji_131',
    '/:gift': 'emoji_132',
    '[Packet]': 'emoji_133',
    '[Rich]': 'emoji_134',
    '[Blessing]': 'emoji_135',
    '[Fireworks]': 'emoji_136',
  };
  static RegExp codeReg = RegExp(
      '/::\\)|/::~|/::B|/::\\||/:8-\\)|/::<|/::\\${r'$'}|/::X|/::Z|/::\'\\(|/::-\\||/::@|/::P|/::D|/::O|/::\\(|\\[囧\\]|/::Q|/::T|/:,@P|/:,@-D|/::d|/:,@o|/:\\|-\\)|/::!|/::L|/::>|/::,@|/:,@f|/::-S|/:\\?|/:\\,@x|/:\\,@@|/:\\,@!|/:!!!|/:xx|/:bye|/:wipe|/:dig|/:handclap|/:B-\\)|/:<@|/:@>|/::-O|/:>-\\||/:P-\\(|/::\'\\||/:X-\\)|/::\\*|/:8\\*|/:pd|/:\\<W\\>|/:beer|/:coffee|/:pig|/:rose|/:fade|/:showlove|/:heart|/:break|/:cake|/:bome|/:shit|/:moon|/:sun|/:hug|/:strong|/:weak|/:share|/:v|/:@\\)|/:jj|/:@@|/:ok|/:jump|/:shake|/:\\<O\\>|/:circle|\\[Happy\\]|\\[Sick\\]|\\[Flushed\\]|\\[Lol\\]|\\[Terror\\]|\\[LetDown\\]|\\[Duh\\]|\\[Hey\\]|\\[Facepalm\\]|\\[Smirk\\]|\\[Smart\\]|\\[Concerned\\]|\\[Yeah!\\]|\\[Onlooker\\]|\\[GoForIt\\]|\\[Sweats\\]|\\[OMG\\]|\\[Emm\\]|\\[Respect\\]|\\[Doge\\]|\\[NoProb\\]|\\[MyBad\\]|\\[Wow\\]|\\[Boring\\]|\\[Awesome\\]|\\[LetMeSee\\]|\\[Sigh\\]|\\[Hurt\\]|\\[Broken\\]|\\[Worship\\]|\\[Party\\]|/:gift|\\[Packet\\]|\\[Rich\\]|\\[Blessing\\]|\\[Fireworks\\]');

  /// 表情code转中文描述
  static String emojiCodeToCN(String text) {
    List<String> emojis = [];
    Iterable<RegExpMatch> match = EmojiUtil.codeReg.allMatches(text).toList();
    for (Match i in match) {
      emojis.add(text.substring(i.start, i.end));
    }
    // List cnList = EmojiUtil.emojiCN.keys.toList();
    emojis.forEach((item) {
      EmojiUtil.emojiCN.forEach((key, value) {
        if (item == value) {
          text = text.replaceAll(item, key);
        }
      });
    });
    return text;
  }

  /// 表情文本转code处理
  static String emojiCNToCode(String text) {
    List<String> emojis = [];
    RegExp reg = RegExp(r'(\[([\u4E00-\u9FA5]{1,3})\]){1}|(\[OK\]){1}');
    Iterable<RegExpMatch> match = reg.allMatches(text).toList();
    for (Match i in match) {
      emojis.add(text.substring(i.start, i.end));
    }
    emojis.forEach((item) {
      text = text.replaceAll(item, EmojiUtil.emojiCN[item] ?? item);
    });
    return text;
  }
}
